"""Record/check numerical outputs across changes, independently of timing metadata.

Run before modifying the calculation core:
    uv run python scripts/check_solver_baseline.py --record /tmp/solver-baseline.npz
Then after changes:
    uv run python scripts/check_solver_baseline.py --check /tmp/solver-baseline.npz

The reference is not regenerated by --check. Existing reference files are never
overwritten. NPZ contains only numeric/text arrays and is read without pickle.
"""

from __future__ import annotations

import argparse
from copy import deepcopy
import hashlib
from pathlib import Path

import numpy as np
import pandas as pd

from pywp.models import Point3D, TrajectoryConfig
from pywp.planner import TrajectoryPlanner
from pywp.planner_validation import DLS_VALIDATION_TOLERANCE_DEG_PER_30M
from pywp.segments import BuildSegment, HoldSegment, VerticalSegment
from pywp.trajectory import WellTrajectory


ROOT = Path(__file__).resolve().parents[1]
STATION_COLUMNS = ["MD_m", "INC_deg", "AZI_deg", "X_m", "Y_m", "Z_m", "DLS_deg_per_30m"]


def baseline_cases():
    common = dict(
        md_step_m=10,
        md_step_control_m=2,
        lateral_tolerance_m=30,
        vertical_tolerance_m=2,
        entry_inc_target_deg=86,
        entry_inc_tolerance_deg=2,
        dls_build_max_deg_per_30m=6,
        max_total_md_postcheck_m=20000,
        turn_solver_max_restarts=0,
        kop_min_vertical_m=550,
    )
    for name, offset in (
        ("ordinary", (0, 0, 0)),
        ("projected_crs", (598863, 7411139, 0)),
    ):
        points = [
            Point3D(x + offset[0], y + offset[1], z + offset[2])
            for x, y, z in ((0, 0, 0), (600, 800, 2400), (1500, 2000, 2500))
        ]
        yield name, points, TrajectoryConfig(**common), False
    radius = 30 * 180 / np.pi / 3
    t1y, t1z = radius * 0.5, 550 + radius * np.sin(np.pi / 3)
    yield (
        "classic_j",
        [
            Point3D(0, 0, 0),
            Point3D(0, t1y, t1z),
            Point3D(0, t1y + 1000, t1z + 1000 / np.tan(np.pi / 3)),
        ],
        TrajectoryConfig(
            **{
                **common,
                "entry_inc_target_deg": 60,
                "max_inc_deg": 70,
                "dls_build_max_deg_per_30m": 3,
                "j_profile_policy": "prefer",
            }
        ),
        False,
    )
    yield (
        "multi_horizontal",
        [
            Point3D(0, 0, 0),
            Point3D(600, 800, 2400),
            Point3D(1500, 2000, 2500),
            Point3D(2200, 2933.333333, 2500),
        ],
        TrajectoryConfig(**common),
        True,
    )


def collect_baseline() -> dict[str, np.ndarray]:
    outputs = {}
    for name, points, config, multi in baseline_cases():
        before_points, before_config = deepcopy(points), config.model_dump()

        def solve():
            planner = TrajectoryPlanner()
            if multi:
                return planner.plan_multi_target(
                    surface=points[0],
                    targets=tuple(points[1:]),
                    config=config,
                    horizontal_start_at_second_target=True,
                )
            return planner.plan(
                surface=points[0], t1=points[1], t3=points[2], config=config
            )

        first, second = solve(), solve()
        pd.testing.assert_frame_equal(first.stations, second.stations, check_exact=True)
        assert points == before_points and config.model_dump() == before_config
        stations = first.stations
        assert np.isfinite(stations[STATION_COLUMNS[:-1]].to_numpy()).all()
        assert stations.MD_m.iloc[0] == 0 and np.all(np.diff(stations.MD_m) > 0)
        assert stations.INC_deg.max() <= config.max_inc_deg + 1e-6
        assert stations.MD_m.iloc[-1] <= config.max_total_md_postcheck_m
        target = points[-1]
        xyz_error = stations[["X_m", "Y_m", "Z_m"]].iloc[-1].to_numpy() - [
            target.x,
            target.y,
            target.z,
        ]
        assert np.hypot(*xyz_error[:2]) <= config.lateral_tolerance_m
        assert abs(xyz_error[2]) <= config.vertical_tolerance_m
        for segment, limit in config.dls_limits_deg_per_30m.items():
            mask = stations.segment.str.startswith(segment)
            values = stations.loc[mask, "DLS_deg_per_30m"].dropna()
            if len(values):
                assert values.max() <= limit + DLS_VALIDATION_TOLERANCE_DEG_PER_30M
        outputs[f"{name}:stations"] = stations[STATION_COLUMNS].to_numpy(dtype=float)
        outputs[f"{name}:segments"] = stations.segment.to_numpy(dtype=str)
        outputs[f"{name}:config"] = np.array(config.model_dump_json())
        print(
            f"SOLVER {name}: {len(stations)} stations, invariants/repeat/input preservation PASS",
            flush=True,
        )

    # Many inexpensive ordinary profiles also exercise exact legacy sampling,
    # including a near-duplicate final sample inside the vertical segment.
    for index in range(12):
        trajectory = WellTrajectory(
            [
                VerticalSegment(400.000000134 + index * 2),
                BuildSegment(0, 30 + index, 3, 10 * index),
                HoldSegment(50 + index, 30 + index, 10 * index),
                BuildSegment(30 + index, 86, 3, 10 * index),
            ]
        )
        outputs[f"sampling:{index}"] = trajectory.stations(10)[
            ["MD_m", "INC_deg", "AZI_deg"]
        ].to_numpy()
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--record", type=Path)
    group.add_argument("--check", type=Path)
    args = parser.parse_args()
    if args.record and args.record.exists():
        parser.error(
            "Reference already exists; choose a new path (never overwrite a baseline)."
        )
    results = collect_baseline()
    if args.record:
        fingerprints = {
            name: hashlib.sha256((ROOT / "pywp" / name).read_bytes()).hexdigest()
            for name in ("segments.py", "trajectory.py", "mcm.py", "planner.py")
        }
        results["source_fingerprints"] = np.array(str(fingerprints))
        with args.record.open("xb") as handle:
            np.savez_compressed(handle, **results)
        print(f"BASELINE RECORDED: {args.record}")
    else:
        with np.load(args.check, allow_pickle=False) as reference:
            assert set(reference.files) - {"source_fingerprints"} == set(results)
            for key, actual in results.items():
                # Stronger than an engineering tolerance for these unchanged
                # cases: every station value, label and config must be exact.
                np.testing.assert_array_equal(actual, reference[key], err_msg=key)
        print(
            "BASELINE: all four solver cases and 12 sampling profiles unchanged exactly"
        )


if __name__ == "__main__":
    main()
